#!/usr/bin/env python3
"""Extract baked font/icon glyph data for the host render-preview harness.

ESPHome's real build (esphome compile) rasterizes every font/icon via
FreeType and bakes the resulting bitmaps into main.cpp as plain byte
arrays, right next to a `new(font_10) font::Font(...)` placement-new call.
That's the exact same data the physical device measures/draws with - so
rather than re-rasterizing fonts ourselves (which would only ever be an
approximation), this pulls those exact arrays out of an existing build and
turns each one into a plain global `font::Font` object the harness can
link against directly.

Usage: python3 tools/extract_preview_fonts.py <path to generated main.cpp> \
           <output header path> <font_id> [<font_id> ...]

Re-run this if fonts.yaml or mdi_substitutions.yaml change size/family/bpp -
the harness's font metrics would otherwise silently drift from the device.
"""
import re
import sys


def extract(main_cpp_text: str, font_id: str) -> str:
    ctor_re = re.compile(rf"^(\s*)new\({font_id}\) font::Font\((.+)\);\s*$")
    lines = main_cpp_text.splitlines()
    for i, line in enumerate(lines):
        m = ctor_re.match(line)
        if not m:
            continue
        data_line = lines[i - 2]
        glyph_line = lines[i - 1]
        args = m.group(2)
        data_m = re.search(r"uint8_t (uint8_t_id\w*)\[\]\s*PROGMEM\s*=\s*(\{.+\});", data_line)
        glyph_m = re.search(r"font::Glyph (font_glyph_id\w*)\[\]\s*=\s*(\{.+\});", glyph_line)
        if not data_m or not glyph_m:
            raise ValueError(f"unexpected layout above new({font_id}) at line {i + 1}")
        data_id, data_body = data_m.group(1), data_m.group(2)
        glyph_id, glyph_body = glyph_m.group(1), glyph_m.group(2)
        # Args are "font_glyph_id_N, count, baseline, height, descender, xheight, capheight, bpp" -
        # drop the leading glyph-array name, we reference it by our own identifier below.
        ctor_rest = args.split(",", 1)[1]
        unique = f"_{font_id}"
        out_data_id = data_id + unique
        out_glyph_id = glyph_id + unique
        # The glyph table's entries reference the byte array by its ORIGINAL
        # name (e.g. "(uint8_t_id_6 + 0)") - rewrite those to match the
        # renamed array, word-boundary guarded so "uint8_t_id" doesn't also
        # match as a prefix of "uint8_t_id_6".
        glyph_body = re.sub(rf"\b{re.escape(data_id)}\b", out_data_id, glyph_body)
        return (
            f"static constexpr uint8_t {out_data_id}[] = {data_body};\n"
            f"static const esphome::font::Glyph {out_glyph_id}[] = {glyph_body};\n"
            f"static esphome::font::Font {font_id}_obj({out_glyph_id},{ctor_rest});\n"
            f"esphome::font::Font *const {font_id} = &{font_id}_obj;\n"
        )
    raise ValueError(f"new({font_id}) font::Font(...) not found")


def main() -> None:
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(1)
    main_cpp_path, out_path, *font_ids = sys.argv[1:]
    with open(main_cpp_path, "r", encoding="utf-8") as f:
        text = f.read()

    blocks = [extract(text, font_id) for font_id in font_ids]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/extract_preview_fonts.py - do not hand-edit.\n")
        f.write("// Exact baked glyph bitmaps pulled from a real ESPHome build's main.cpp,\n")
        f.write("// so get_text_bounds()/print() here match the physical device exactly.\n")
        f.write("#pragma once\n\n")
        f.write("\n".join(blocks))
        f.write("\n")

    print(f"Wrote {len(blocks)} font(s) to {out_path}")


if __name__ == "__main__":
    main()
